### ISSUE TITLE
Update HuBMAP Kidney data

### ISSUE THREAD

**Issue by amberramesh** [amberramesh/tissue-bar-graphs#4]
https://portal.hubmapconsortium.org/search?mapped_data_types[0]=snRNA-seq%20%5BSalmon%5D&mapped_data_types[1]=Slide-seq%20%5BSalmon%5D&origin_sample.mapped_organ[0]=Kidney%20%28Right%29&origin_sample.mapped_organ[1]=Kidney%20%28Left%29&entity_type[0]=Dataset 
(Requires access)

Additional datasets need to be run through Azimuth using:
https://github.com/hubmapconsortium/hra-azimuth-predictions

Cell predictions file need to be run through an aggregator, such as
https://github.com/hubmapconsortium/hra-azimuth-predictions

Add the aggregated counts for new datasets in the static branch
https://github.com/hubmapconsortium/tissue-bar-graphs/tree/static/csv/Kidney_HuBMAP_Portal

**Comment by vickydaiya** [comment]
Some datasets do not have an h5 file on the server which results in a 404 error and terminates the program. Can I modify the download.py to skip over 404 errors and continue downloading other datasets by showing the "skipping dataset" message in the download log?

**Comment by vickydaiya** [comment]
Finished updating Kidney HuBMAP data on the portal [HRA tissue blocks](https://hubmapconsortium.github.io/tissue-bar-graphs/) (05/18/22)
